import { Metadata } from "next"; 
import { Outfit } from "next/font/google";
import { Shadows_Into_Light_Two } from "next/font/google";
import "@/app/assets/style/globals.css";
import Header from '@/app/component/Header/Header'
import Footer from '@/app/component/Footer/Footer'

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  variable: "--font-outfit",
});

const shadowsTwo = Shadows_Into_Light_Two({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--font-shadows_two",
});


export const CustomMetadata = {
  title: "Agriculture Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${shadowsTwo.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
